import map from "./assets/map.gif";

const contactUs = () => {
  const contactUs = document.getElementById("contact-us");
  const headerGrp = document.createElement("hgroup");
  const heading = document.createElement("h2");
  const subHeading = document.createElement("p");
  const mainContainer = document.createElement("div");
  const formContainer = document.createElement("div");
  formContainer.id = "formContainer";
  const MapContainer = document.createElement("div");
  mainContainer.id = "mainContainer";
  heading.textContent = "Contact our Experts";
  subHeading.textContent = "Expert Guidance at your Fingertips";
  headerGrp.appendChild(heading);
  headerGrp.appendChild(subHeading);
  const form = document.createElement("form");
  const fullNameLocationContainer = document.createElement("div");
  const labelInputContainer = document.createElement("div");
  const contactInfoContainer = document.createElement("div");
  const buttonContainer = document.createElement("div");
  buttonContainer.id = "buttonContainer";
  const submitButton = document.createElement("button");
  const fullNameLabel = document.createElement("label");
  fullNameLabel.textContent = "Full Name";
  const firstName = document.createElement("input");
  const lastName = document.createElement("input");
  labelInputContainer.appendChild(firstName);
  labelInputContainer.appendChild(lastName);
  const locationLabel = document.createElement("label");
  const location = document.createElement("input");
  locationLabel.textContent = "Location";
  fullNameLabel.appendChild(labelInputContainer);
  locationLabel.appendChild(location);
  fullNameLocationContainer.appendChild(fullNameLabel);
  fullNameLocationContainer.appendChild(locationLabel);
  const emailLabel = document.createElement("label");
  emailLabel.textContent = "Email";
  const email = document.createElement("input");
  email.placeholder = "sample@gmail.com";
  const phoneNumberLabel = document.createElement("label");
  phoneNumberLabel.textContent = "Phone number";
  const phoneNumber = document.createElement("input");
  phoneNumber.placeholder = "Phone number";
  const descriptionLabel = document.createElement("label");
  const descriptionCase = document.createElement("textarea");
  descriptionLabel.textContent = "Describe your case";
  descriptionCase.placeholder = "Tell us about your use case...";
  submitButton.textContent = "Submit";
  const rightArrowIcon = document.createElement("img");
  rightArrowIcon.src =
    "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxZW0iIGhlaWdodD0iMWVtIiB2aWV3Qm94PSIwIDAgMTAyNCAxMDI0Ij48cGF0aCBmaWxsPSJ3aGl0ZSIgZD0iTTMzOC43NTIgMTA0LjcwNGE2NCA2NCAwIDAgMCAwIDkwLjQ5NmwzMTYuOCAzMTYuOGwtMzE2LjggMzE2LjhhNjQgNjQgMCAwIDAgOTAuNDk2IDkwLjQ5NmwzNjIuMDQ4LTM2Mi4wNDhhNjQgNjQgMCAwIDAgMC05MC40OTZMNDI5LjI0OCAxMDQuNzA0YTY0IDY0IDAgMCAwLTkwLjQ5NiAwIi8+PC9zdmc+";
  submitButton.appendChild(rightArrowIcon);
  const mapGif = document.createElement("img");
  mapGif.src = map;
  MapContainer.appendChild(mapGif);
  emailLabel.appendChild(email);
  phoneNumberLabel.appendChild(phoneNumber);
  descriptionLabel.appendChild(descriptionCase);
  contactInfoContainer.appendChild(emailLabel);
  contactInfoContainer.appendChild(phoneNumberLabel);
  contactInfoContainer.appendChild(descriptionLabel);
  buttonContainer.appendChild(submitButton);
  form.appendChild(fullNameLocationContainer);
  form.appendChild(contactInfoContainer);
  form.appendChild(buttonContainer);
  formContainer.appendChild(form);
  mainContainer.appendChild(formContainer);
  mainContainer.appendChild(MapContainer);
  contactUs.appendChild(headerGrp);
  contactUs.appendChild(mainContainer);
  return contactUs;
};

export { contactUs };
